import React, { useState, useEffect } from "react";
import { FaDownload, FaEye, FaEnvelope, FaSpinner, FaCheckCircle, FaTimesCircle, FaExclamationCircle } from "react-icons/fa";
import reportService from "../services/reportService";
import PreviewModal from "./PreviewModal";
import EmailDialog from "./EmailDialog";

function ReportHistory({ reports, onRefreshHistory }) {
  const [previewOpen, setPreviewOpen] = useState(false);
  const [previewBlobUrl, setPreviewBlobUrl] = useState("");
  const [previewReportName, setPreviewReportName] = useState("");

  const [emailOpen, setEmailOpen] = useState(false);
  const [selectedReportId, setSelectedReportId] = useState(null);
  const [selectedReportName, setSelectedReportName] = useState("");

  const [downloadingId, setDownloadingId] = useState(null);

  useEffect(() => {
    const hasActiveJob = reports.some(r => r.status === "PENDING" || r.status === "IN_PROGRESS");
    if (!hasActiveJob) return;

    const interval = setInterval(() => {
      onRefreshHistory();
    }, 3000);

    return () => clearInterval(interval);
  }, [reports, onRefreshHistory]);

  const handleDownload = async (id, name) => {
    setDownloadingId(id);
    try {
      const blob = await reportService.download(id);
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = name.endsWith(".pdf") ? name : `${name}.pdf`;
      document.body.appendChild(a);
      a.click();
      a.remove();
      window.URL.revokeObjectURL(url);
    } catch (error) {
      alert("Failed to download PDF file.");
    } finally {
      setDownloadingId(null);
    }
  };

  const handlePreview = async (id, name) => {
    setPreviewReportName(name);
    setPreviewBlobUrl("");
    setPreviewOpen(true);

    try {
      const blob = await reportService.download(id);
      const url = window.URL.createObjectURL(blob);
      setPreviewBlobUrl(url);
    } catch (error) {
      alert("Failed to retrieve PDF for preview.");
      setPreviewOpen(false);
    }
  };

  const triggerEmail = (id, name) => {
    setSelectedReportId(id);
    setSelectedReportName(name);
    setEmailOpen(true);
  };

  const handleEmailSuccess = (msg) => {
    alert(msg);
  };

  const formatSize = (bytes) => {
    if (!bytes) return "0 KB";
    return (bytes / 1024).toFixed(1) + " KB";
  };

  const renderStatus = (status) => {
    switch (status) {
      case "COMPLETED":
        return (
          <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-semibold bg-[#10B981]/10 text-[#10B981] border border-[#10B981]/20">
            <FaCheckCircle /> Completed
          </span>
        );
      case "FAILED":
        return (
          <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-semibold bg-[#EF4444]/10 text-[#EF4444] border border-[#EF4444]/20">
            <FaTimesCircle /> Failed
          </span>
        );
      case "IN_PROGRESS":
        return (
          <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-semibold bg-sky-500/10 text-sky-400 border border-sky-500/20">
            <FaSpinner className="animate-spin" /> Generating
          </span>
        );
      default:
        return (
          <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-semibold bg-[#F59E0B]/10 text-[#F59E0B] border border-[#F59E0B]/20">
            <FaExclamationCircle /> Queued
          </span>
        );
    }
  };

  return (
    <div className="bg-slate-900 rounded-[24px] border border-slate-800 shadow-[0_20px_50px_rgba(0,0,0,0.45)] overflow-hidden animate-fade-in">
      <div className="overflow-x-auto">
        <table className="min-w-full divide-y divide-slate-800 text-left text-sm">
          <thead className="bg-slate-950/40 text-xs font-bold text-slate-400 uppercase tracking-wider">
            <tr>
              <th className="px-8 py-4">Report Name</th>
              <th className="px-8 py-4">Report Type</th>
              <th className="px-8 py-4">Status</th>
              <th className="px-8 py-4">Generated At</th>
              <th className="px-8 py-4">Generated By</th>
              <th className="px-8 py-4">Size</th>
              <th className="px-8 py-4 text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-800 text-white">
            {reports.map((report) => (
              <tr key={report.id} className="hover:bg-slate-800/40 transition-colors duration-200">
                <td className="px-8 py-5 font-bold text-white">
                  {report.name}
                </td>
                <td className="px-8 py-5 capitalize text-slate-400">{report.reportType}</td>
                <td className="px-8 py-5">{renderStatus(report.status)}</td>
                <td className="px-8 py-5 text-slate-400">
                  {new Date(report.generatedTime).toLocaleString()}
                </td>
                <td className="px-8 py-5 text-slate-400">{report.generatedBy}</td>
                <td className="px-8 py-5 text-slate-400">{formatSize(report.fileSize)}</td>
                <td className="px-8 py-5 text-right space-x-2">
                  {report.status === "COMPLETED" ? (
                    <>
                      <button
                        onClick={() => handlePreview(report.id, report.name)}
                        title="Preview PDF"
                        className="p-2.5 text-slate-400 hover:text-sky-400 hover:bg-slate-800/50 rounded-xl border border-transparent hover:border-slate-800 transition-all duration-200"
                      >
                        <FaEye size={14} />
                      </button>
                      <button
                        onClick={() => handleDownload(report.id, report.name)}
                        title="Download PDF"
                        disabled={downloadingId === report.id}
                        className="p-2.5 text-slate-400 hover:text-emerald-400 hover:bg-slate-800/50 rounded-xl border border-transparent hover:border-slate-800 transition-all duration-200 disabled:opacity-50"
                      >
                        {downloadingId === report.id ? (
                          <FaSpinner className="animate-spin" size={14} />
                        ) : (
                          <FaDownload size={14} />
                        )}
                      </button>
                      <button
                        onClick={() => triggerEmail(report.id, report.name)}
                        title="Email PDF"
                        className="p-2.5 text-slate-400 hover:text-cyan-400 hover:bg-slate-800/50 rounded-xl border border-transparent hover:border-slate-800 transition-all duration-200"
                      >
                        <FaEnvelope size={14} />
                      </button>
                    </>
                  ) : (
                    <span className="text-xs text-slate-400 italic">Processing</span>
                  )}
                </td>
              </tr>
            ))}
            {reports.length === 0 && (
              <tr>
                <td colSpan="7" className="px-8 py-12 text-center text-slate-400">
                  No compiled reports found in your database history.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>

      <PreviewModal
        isOpen={previewOpen}
        onClose={() => {
          setPreviewOpen(false);
          if (previewBlobUrl) {
            window.URL.revokeObjectURL(previewBlobUrl);
          }
        }}
        pdfBlobUrl={previewBlobUrl}
        reportName={previewReportName}
      />

      <EmailDialog
        isOpen={emailOpen}
        onClose={() => setEmailOpen(false)}
        reportId={selectedReportId}
        reportName={selectedReportName}
        onEmailSent={handleEmailSuccess}
      />
    </div>
  );
}

export default ReportHistory;
